### ISSUE TITLE
The trained model for ResNet-18 backbone is not available on Google Drive

### ISSUE THREAD

**Issue by vBLFTePebWNi6c** [Tangshitao/ClipShots_basline#3]
The archive is empty

**Comment by rsomani95** [comment]
Did you try the Baidu link?

**Comment by ArtanisCV** [comment]
You may find it here.
https://github.com/kenshohara/3D-ResNets-PyTorch

**Comment by kaylC4** [comment]
Did someone find the solution for the google drive archive?

thank you so much

**Comment by Tangshitao** [comment]
Update google dirve link
